### ISSUE TITLE
Crossposts sorting

### ISSUE THREAD

**Issue by Redstone-Hamster** [LilyAsFlora/reddit-fetch#2]
Whenever I set allowCrossPosts to false it can't find any posts matching the criteria

**Comment by LilyAsFlora** [comment]
That meant the only data it could find were crossposts.

**Comment by LilyAsFlora** [comment]
I'll look into the issue.

**Comment by LilyAsFlora** [comment]
Fixed `v1.2.2`. Thank you for the report!
